In [5]:
import numpy as np
a = np.random.random((3,4))
print("\nArray: \n",a)
b = np.zeros((3,4))
print("\n Array with zeros: \n",b)
c = np.arange(5,31,2)
print("\n Array of step size 2: \n",c)
print("\nShape: \n",a.shape)
print("\nDimension: \n",a.ndim)
print("\nDatatype: \n",a.dtype)
print("\nFlatten array: \n",a.flatten())



Array: 
 [[0.52738136 0.82376091 0.54762448 0.41803377]
 [0.94970019 0.86404104 0.79292477 0.49110192]
 [0.04873819 0.89160768 0.20947132 0.08973897]]

 Array with zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Array of step size 2: 
 [ 5  7  9 11 13 15 17 19 21 23 25 27 29]

Shape: 
 (3, 4)

Dimension: 
 2

Datatype: 
 float64

Flatten array: 
 [0.52738136 0.82376091 0.54762448 0.41803377 0.94970019 0.86404104
 0.79292477 0.49110192 0.04873819 0.89160768 0.20947132 0.08973897]
