In [1]:
import numpy as np
a = np.array([1,2,3])
print("One dimensional array:",a)

One dimensional array: [1 2 3]


In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print("Two dimensional array:",a)

Two dimensional array: [[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Three dimensional array:",a)

Three dimensional array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
a = np.zeros((2,2))
print("\n Array with zero values: \n",a)


 Array with zero values: 
 [[0. 0.]
 [0. 0.]]


In [5]:
import numpy as np
a = np.random.random((2,2))
print("\n Random values:\n",a)


 Random values:
 [[0.98919753 0.78687739]
 [0.12483877 0.14623904]]


In [10]:
import numpy as np
a = np.arange(0,100,10)
print("\n Sequence array:\n",a)


 Sequence array:
 [ 0 10 20 30 40 50 60 70 80 90]


In [13]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = a.reshape(3,4)
print("\n Original array: \n",a)
print("\n New array: \n",b)


 Original array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 New array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = a.flatten()
print("\n Original array: \n",a)
print("\n New array:\n",b)



 Original array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 New array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
b = a.flatten()
print("\n Original array: \n",a)
print("\n New array:\n",b)
print("\n No.of dimensions: \n",a.ndim)


 Original array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

 New array:
 [1 2 3 4 5 6 1 2 3 4 5 6]

 No.of dimensions: 
 3


In [29]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("Shape of the array",a.shape)

Shape of the array (4, 3)


In [30]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("\n Array element:\n",a.dtype)


 Array element:
 int64


In [31]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
size = len(a)
print("\n Size of the array:\n",size)


 Size of the array:
 4


In [1]:
import numpy as np
a = [1,2,3]
a = np.array(a)
new = a.astype('float64')
print(new)
print(new.dtype)

[1. 2. 3.]
float64
