In [8]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
slice1 =a[2:6]
print("sliced array = ",slice1)

sliced array =  [3 4 5 6]


In [9]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
slice1 = a[::2]
print("Array of step 2 = ",slice1)


Array of step 2 =  [1 3 5 7 9]


In [10]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
slice1 = a[::3]
print("Array of step 3 = ",slice1)

Array of step 3 =  [1 4 7]


In [11]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
slice1 = a[::-1]
print("Reversed array = ",slice1)

Reversed array =  [9 8 7 6 5 4 3 2 1]


In [15]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray = a[0:2,1:3]
print("Sliced multidimensional array = \n",subarray)

Sliced multidimensional array = 
 [[2 3]
 [5 6]]


In [16]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray = a[:2,:1]
print(subarray)

[[1]
 [4]]


In [20]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
col1 = a[:,0]
print("Extracted first column = ",col1)

Extracted first column =  [1 4 7]


In [23]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
row1 = a[0,:]
print("Extracted first row = ",row1)

Extracted first row =  [1 2 3]


In [27]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
row1 = a[0:2:1]
print("rows = \n",row1)

rows = 
 [[1 2 3]
 [4 5 6]]


In [28]:
#array indicing for 1D array
import numpy as np
import array
a = array.array('i',[10,20,30,40,50])
print(a[0])
print(a[3])

10
40


In [29]:
#array indicing for 2D array
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0])
print(a[2,1])

1
8


In [34]:
#Indexing technique
#Basic indexing
import numpy as np
a = np.array([10,20,30,40,50])
print("Basic indexing = ",a[1])

#Negative indexing
print("Negative indexing = ",a[-1])

#Slicing indexing
print("Slicing indexing = ",a[1:4])

#Boolean indexing
arr = np.array([10,20,30,40,50])
print("Boolean indexing = ",arr[arr>25])

#Fancy indexing
arr = np.array([10,20,30,40,50])
print("Fancy indexing = ",arr[[1,3]])

Basic indexing =  20
Negative indexing =  50
Slicing indexing =  [20 30 40]
Boolean indexing =  [30 40 50]
Fancy indexing =  [20 40]


In [4]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
result = np.hstack((a,b))
print("Horizontal join = \n",result)

Horizontal join = 
 [[1 2 5 6]
 [3 4 7 8]]


In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
result = np.vstack((a,b))
print("Vertical join = \n",result)

Vertical join = 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
result = np.dstack((a,b))
print("Depth join = \n",result)

Depth join = 
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [10]:
import numpy as np
a = np.array([1,2,3,4,5,6])
result = np.array_split(a,3)
print("Splitted array = \n",result)

Splitted array = 
 [array([1, 2]), array([3, 4]), array([5, 6])]
