In [3]:
import numpy as np
a =np.array([1,6,2,7,6,4])
x = np.where(a==6)
y = np.where(a==7)
print(x)
print(y)

(array([1, 4]),)
(array([3]),)


In [5]:
import numpy as np
a =np.array([1,6,2,7,6,4])
x = np.where(a%2==0)
y = np.where(a%3==1)
print(x)
print(y)

(array([1, 2, 4, 5]),)
(array([0, 3, 5]),)


In [10]:
import numpy as np
a =np.array([0,1,2,2,7,8,9])
x = np.searchsorted(a,8,side='right')
y = np.searchsorted(a,8,side='left')
print("Left= ",y)
print("Right= ",x)


Left=  5
Right=  6


In [12]:
import numpy as np
a = np.array([9,5,2,7,6,4])
print(np.sort(a))
b = np.array([[7,4,9],[9,1,4]])
print(np.sort(b))

[2 4 5 6 7 9]
[[4 7 9]
 [1 4 9]]


In [15]:
import numpy as np
a = np.array([31,78,69,88])
x = [False,True,True,False]
new = a[x]
print(x)
print(new)


[False, True, True, False]
[78 69]


In [16]:
import numpy as np
a = np.array([31,78,69,88])
filter_a = a>70
new = a[filter_a]
print(filter_a)
print(new)


[False  True False  True]
[78 88]
